src/requests/sasl_authenticate_request.ts

there is obviously a bug causing inability to connect to rabbitmq instances where the username password is not the same

fix username duplicity

---

src/connection.ts
src/producer.ts
src/requests/delete_publisher_request.ts
src/response_decoder.ts
src/responses/delete_publisher_response.ts
test/unit/delete_publisher.test.ts

Hello! This PR adds the DeletePublisher Command
https://github.com/rabbitmq/rabbitmq-server/blob/1ee8454129b7769fda6dfc1a528e886b290aa258/deps/rabbitmq_stream/docs/PROTOCOL.adoc#deletepublisher
connection.ts can handle sending DeletePublisher requests, and parsing DeletePublisherResponse.
I also exposed the publishingId on the producer class, since publishingId is required in DeletePublisherRequest. 
Tests passing with `npm run test`

DeletePublisher Command

---

src/client.ts
test/e2e/connection_closed_listener.test.ts
test/support/util.ts

Closes #104 
On socket disconnect, a user-provided function can be called, if specified.
This callback, linked to the underlying socket event, can be specified:
for locator clients, among the listeners field passed to the Client.connect function. Such a callback is specific for the locator connection and is not linked to connection events related to publisher/consumer instances created from the locator.
for publishers and consumers, as a field in the parameters of declarePublisher and declareConsumer. Such callbacks are specific for the single publisher/consumer.

104 disconnect hook (clean)

---

src/client.ts
src/publisher.ts

I did not rename "locator" since I could not find a more fitting name. `isClosed` was renamed to `closed` and the `consumerRef` for the SuperStream consumer is now randomly assigned

153 59 ability to consume messages from superstream typos

---

src/client.ts
src/connection.ts
src/requests/peer_properties_request.ts
test/e2e/connect.test.ts
test/e2e/declare_consumer.test.ts
test/e2e/declare_publisher.test.ts
test/support/fake_data.ts
test/support/rabbit.ts

closes https://github.com/coders51/rabbitmq-stream-js-client/issues/173

Specify connection name when creating a client

---

README.md
src/requests/create_stream_request.ts
test/support/rabbit.ts
test/unit/create_stream.test.ts
test/unit/create_super_stream.test.ts

Creation stream arguments were ignored because the property key started with `x-`.
Moreover the  `queue-leader-locator` argument can take up to 3 values which are `random`, `client-local` and `least-leaders`.
Also, the `max-age` argument is a string of numbers ending with a trailing `s`

[bug] creation of stream with arguments

---

README.md
example/package-lock.json
example/src/autoreconnect_example.js
src/client.ts
src/connection.ts
src/consumer.ts
src/heartbeat.ts
src/publisher.ts
src/requests/subscribe_request.ts
src/super_stream_publisher.ts
test/e2e/client_restart.test.ts
test/e2e/connection_closed_listener.test.ts
test/unit/publisher.test.ts

Update readme and add example to show how one might manage auto reconnecting

---

src/client.ts
src/super_stream_consumer.ts
test/e2e/superstream_consumer.test.ts

```js
client.declareSuperStreamConsumer(
{
superStream: superStreamName
// consumerRef: "super-stream-[random-uuid]", as default, can not change
// offset: Offset.first(), as default, can not change
},
(message: Message) => {
// handle message logic
})
```
```js
client.declareSuperStreamConsumer(
{
superStream: superStreamName,
consumerRef: "consumer-group-name", // defined by user
offset: Offset.next() // defined by user
},
(message: Message) => {
// handle message logic
})
```

feat(super-stream): enable customized consumerRef, offset

---

.github/workflows/main.yml
example/package.json
src/client.ts
src/connection.ts
src/consumer.ts
src/publisher.ts
test/e2e/address_resolver.test.ts
test/e2e/close_consumer.test.ts
test/e2e/declare_consumer.test.ts
test/e2e/declare_publisher.test.ts
test/e2e/metadata_update.test.ts
test/e2e/offset.test.ts
test/e2e/publish_confirm.test.ts
test/support/fake_data.ts
test/support/rabbit.ts

Close publishers and consumers upon metadata update

---

src/client.ts
src/connection.ts
src/connection_pool.ts
src/consumer.ts
src/publisher.ts
src/util.ts
test/e2e/close_consumer.test.ts
test/e2e/close_publisher.test.ts
test/e2e/connection_closed_listener.test.ts
test/e2e/declare_consumer.test.ts
test/e2e/declare_publisher.test.ts
test/e2e/metadata_update.test.ts
test/unit/delete_publisher.test.ts

See Issue https://github.com/coders51/rabbitmq-stream-js-client/issues/197 for more details

197 check if cached connection can support more pubsubs before reusing

---

example/package-lock.json
example/src/offset_tracking_receive.js
example/src/offset_tracking_send.js
src/consumer.ts

When the consumer is closed we should stop handling the incoming messages in the stream. 
This beahviour has been seen on the offset tracking example of rabbitmq nodejs stream tutorials [here](https://github.com/rabbitmq/rabbitmq-tutorials/pull/445), with two sends in sequence, the consumer would read the queue until the end, instead of closing at the first marker found.

feat: block message handler execution if consumer is closed

---

.github/workflows/main.yml
.gitignore
Makefile
README.md
conf/enabled_plugins
conf/rabbitmq.conf
docker-compose.yaml
src/client.ts
src/connection.ts
src/requests/sasl_authenticate_request.ts
test/e2e/connect.test.ts
test/support/util.ts

Adds an optional `mechanism` parameter and implements EXTERNAL auth following the Java reference implementation.
Also fixes a broken test.

Add support for EXTERNAL auth

---

src/client.ts
src/super_stream_consumer.ts
test/e2e/superstream_consumer.test.ts

Fixes #217 
---
The active part of the change is adding the property to the consumer:
https://github.com/coders51/rabbitmq-stream-js-client/pull/218/files#diff-25d66d74617fe2e23d7946bd6e3ba95640ab1b9bc8947445d604fc271c7c1f12R490-R492
```ts
if (superStream) {
properties["super-stream"] = superStream
}
```
The rest is plumbing to get the super stream name passed down to the right place.
I have added a test which fails on `main` and passes on this branch. I have included it inside the existing super stream consumer end-to-end test.
I'd be happy to work through any comments or suggested restructures in order to get this in shape to be merged.
Thanks

217 fix super stream consumer property

---

package-lock.json
package.json
src/amqp10/applicationProperties.ts
src/amqp10/messageAnnotations.ts
src/amqp10/messageHeader.ts
src/amqp10/properties.ts
src/response_decoder.ts
test/e2e/declare_consumer.test.ts
test/support/fake_data.ts
test/support/util.ts

- Fix a bug that prevented amqplib's messages to be processed
- Cleaned up code to avoid unnecessary forwards and rewind on data reader

232 error not supported format code 83 when messsage is published using amqplibamqp 091

---

src/client.ts
src/connection.ts
src/connection_pool.ts
src/consumer.ts
src/publisher.ts
test/e2e/stream_cache.test.ts
test/support/fake_data.ts

During testing, we ran into a problem where we would create two connections to different vhosts, each with the same stream name. We could see in the RabbitMQ management interface that the configuration is valid and accessing them individually would work as expected, but when trying to access them at the same time, we would get messages leaking into the wrong vhost.
After debugging the issue, I tracked the root cause to the `ConnectionPool.getCacheKey` function which would build a cache using only the stream name, not the vhost. This meant that we were always getting the cached copy regardless of the actual vhost.
All the other changes are to support that one change and there is a test to confirm the result.

Fix bug when connecting to the same stream name different vhosts

---

README.md
example/package-lock.json
example/src/single_active_consumer_update_example.js
src/client.ts
src/connection.ts
src/consumer.ts
test/e2e/declare_consumer.test.ts

This pr adds a consumer update listener in the consumer. In this way, the end user can customize the behaviour of a single active consumer when it becomes active. An example is also added to show how a single active consumer can resume the consuming of messages from a specific offset, upon activation.

wip: single active consumer offset tracking

---

src/client.ts
src/connection_pool.ts
src/consumer.ts
src/publisher.ts

So far we kept the `manuallyClose` param, but the `refCount` and connection caching are managed inside the `ConnectionPool`.

260 refactoring: manage connections inside pool

---

src/client.ts
src/consumer.ts
test/e2e/consumer_offset.test.ts
test/e2e/declare_consumer.test.ts
test/e2e/offset.test.ts

we have added a `getOffset(): bigint` method on the consumer to retrieve the current offset (based on the last message proccesed)
we have also made the offset optional in the `storeOffset(offsetValue?: bigint): Promise<void>` and if not provided the operation will use the internal offset

Some improvement suggestions on Offset manipulation for consumers

---

src/client.ts
src/connection_pool.ts
test/e2e/client_close.test.ts

The socket's close callback resets the "ready" flag on the connection, but not soon enough.
Resorted to catching the error.

fix cannot close client after consumer

---

.github/workflows/main.yml
.mocharc.js
package-lock.json
package.json
src/client.ts
src/consumer.ts
src/publisher.ts
src/super_stream_consumer.ts
src/super_stream_publisher.ts
test/e2e/client_close.test.ts
test/e2e/consumer_offset.test.ts
test/e2e/sub_entry_consume.test.ts

As suggested by @tarzacodes we have wrapped the original StreamConsumer and StreamPublisher, that expose the `manuallyClose` parameter for internal reasons (i.e. callbacks), and created a new interface for each that just expose a parameterless `close()`

262# hide manuallyClose param in close methods
